server:
  ip: 150.158.110.63  # 自定义属性 属性改名任意
  port: 8080
#防止8080和8081冲突


spring:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.110.63:3306/sc?useUnicode=true & characterEncoding=utf-8 & allowPublicKeyRetrieval=true&useSSL=false & serverTimezone=Asia/Shanghai
    username: root
    password: 123abc
    #云服务器要去mysql更新权限
    #服务器与数据库大坑 如果你用编译器连接数据库，定义UTC，MySQL以本地时区进行转换会导致，执行时间比编译器执行时间早8个小时
    #建议用 serverTimezone=Asia/Shanghai   不用UTC
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB #配置文件上传属性


  #可以直接在配置文件中统一配置时间格式
  freemarker:
    cache: false

  web:
    resources:
      static-locations: file:/www/wwwroot/ , classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #服务器的静态资源访问配置   其实默认放在resources/static下即可  通过ip地址:端口 访问

  # mongoDB的远程配置  为了防止扫描攻击 采用账号密码访问   root指定数据库是admin  如果用另外的数据库需要在对应数据库新建user

# ES访问配置 可独立部署在任意一个服务器

#服务器中ES8的配置问题  更新了安全策略 :
  #将config文件夹下的elasticsearch.yml配置文件打开
  #将92和98行两处的 true 改为 false
  #xpack.security.enabled: false
  #xpack.security.http.ssl:
  #  enabled: false
  #通过浏览器访问 http://localhost:9200
  #页面中显示一个json串 , 这样就表示启动ES成功了

  elasticsearch:
    rest:
      # enable host port 自定义属性 是否启用es
      enable: true
      uris: http://150.158.110.63:9200  #集群时需要 用逗号隔开地址
      host: 150.158.110.63
      port: 9200
      username: elastic   # 强制需要用户名
      password: Zb6eQvd99MO7=XX=58GI




# mongoDB的远程配置  为了防止扫描攻击 采用账号密码访问   root指定数据库是admin  如果用另外的数据库需要在对应数据库新建user
  data:
    mongodb:
      host: 150.158.110.63
      port: 27017
      authentication-database: admin
      username: root
      password: 53oOBExixV4ArY64


  # redis配置  如果不写 自动默认配置   如果服务器或者本地没有redis数据库 需要改动很多源文件
  redis:
    #url: redis://user:password@127.0.0.1:6379 #该地址配置以后会重置host,port,password的规则。
    host: 150.158.110.63
    # 在同机器上连接同机器的redis  建议写成localhost
    port: 6379
    password: redis    # 自定义密码
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: -1
        max-wait: 10
        min-idle: 0
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 连接池中的最大空闲连接
  # 连接池中的最小空闲连接
  # 连接超时时间（毫秒）

  #邮箱验证码配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com; 163邮箱是smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1511237570@qq.com
    #授权码
    password: egihlrcyhuwlggbf
    # 昵称  是自定义属性 能引用到即可 无视解析报错
    nickname: PawsHub官方





web:
  uploadPath: /www/wwwroot/ # Win: D:/IdeaProjects/forum/images/


#showSql
# mybatis-plus配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名   #这个是扫描到Entity实体包的路径，可根据自己的配置
  type-aliases-package: com.example.hou.entity
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapperLocations: classpath*:mapper/**Mapper.xml
  #尤其注意这个路径问题啊啊啊啊啊啊啊

  #jwt 暂时不自定义配置


#文心一言模型配置
gear:
  wenxin:
    api-key: 'Ov7A87aDXw1Fbf0Zp6DOE2s2'
    secret-key: 'kXNj66TYV2zYnKOTaKXL8nGDWW22OEQd'